# Generated by Django 4.2.6 on 2023-10-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('Country_code', models.CharField(choices=[('india', '+91'), ('canada', '+1')], max_length=20)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('job_role', models.CharField(choices=[('frontenddeveloper', 'Frontend Developer'), ('backenddeveloper', 'Backend Developer'), ('fullstackdeveloper', 'Fullstack Developer'), ('frontenddeveloper', 'Frontend Developer'), ('uiuxdeveloper', 'Ui/UX Designer')], max_length=19)),
                ('qualification', models.CharField(choices=[('bca', 'BCA'), ('btech', 'Btech'), ('mca', 'MCA'), ('mtech', 'Mtech')], max_length=5)),
                ('experience_year', models.CharField(choices=[('0year', '0 year'), ('1year', '1 year'), ('2year', '2 year'), ('3year', '3 year'), ('4plusyear', '4+ year')], max_length=9)),
                ('experience_month', models.CharField(choices=[('0month', '0 month'), ('1month', '1 month'), ('2month', '2 month'), ('3month', '3 month'), ('4month', '4 month'), ('5month', '5 month')], max_length=6)),
                ('address', models.CharField(max_length=100)),
                ('streetname', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('zipcode', models.TextField(max_length=6)),
            ],
        ),
    ]
