# Generated by Django 4.2.5 on 2023-10-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_no',
            field=models.DateField(),
        ),
    ]
