# Generated by Django 4.2.5 on 2023-10-22 05:58

from django.db import migrations, models
import jobapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_jobapplication_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[jobapp.models.JobApplication.validate_phonenumber]),
        ),
    ]
