# Generated by Django 4.2.6 on 2023-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_jobapplication_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='country_code',
            field=models.CharField(choices=[('', '+91'), ('india', '+91'), ('canada', '+1')], default='+91', max_length=20),
        ),
    ]
